"""Main ETL pipeline orchestrating scraping, cleaning, validation, deduplication, and export."""

import argparse
import csv
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
import sys
import time
from typing import Any, Dict, List, Optional

from config import (
    AppConfig,
    DEFAULT_DATA_QUALITY_REPORT_PATH,
    DEFAULT_LOG_FILE_PATH,
    DEFAULT_SUMMARY_REPORT_PATH,
    load_config,
)
from processing import (
    RECORD_FIELDS,
    ScrapedRecord,
    clean_record,
    clear_all_checkpoints,
    find_duplicates,
    generate_data_quality_report,
    has_checkpoint,
    validate_record,
)
from scrapers import BooksScraper, QuotesScraper


def setup_logging(log_file: Optional[Path] = None) -> logging.Logger:
    """Configure dual-destination logging to console and scraper log file."""
    target_log_file = log_file or DEFAULT_LOG_FILE_PATH
    target_log_file.parent.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    # Avoid duplicate handlers if setup_logging is re-invoked
    if logger.hasHandlers():
        logger.handlers.clear()

    formatter = logging.Formatter(
        fmt="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Console handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    # File handler (UTF-8)
    file_handler = logging.FileHandler(target_log_file, mode="a", encoding="utf-8")
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    return logging.getLogger("ETLPipeline")


def write_summary_report(
    summary_data: Dict[str, Any],
    report_path: Optional[Path] = None,
) -> Path:
    """Write actual execution statistics to summary_report.json with indent=4 and UTF-8 encoding.

    Args:
        summary_data: Dictionary populated dynamically with runtime metrics.
        report_path: Output destination path. Defaults to configured path.

    Returns:
        Path: Target report file path.
    """
    target_path = report_path or DEFAULT_SUMMARY_REPORT_PATH
    target_path.parent.mkdir(parents=True, exist_ok=True)
    with open(target_path, mode="w", encoding="utf-8") as json_file:
        json.dump(summary_data, json_file, indent=4, ensure_ascii=False)
    return target_path


def write_data_quality_report(
    quality_data: Dict[str, Any],
    report_path: Optional[Path] = None,
) -> Path:
    """Write comprehensive data quality metrics to JSON report with indent=4 and UTF-8 encoding.

    Args:
        quality_data: Quality audit dictionary generated by generate_data_quality_report.
        report_path: Output destination path. Defaults to configured path.

    Returns:
        Path: Target report file path.
    """
    target_path = report_path or DEFAULT_DATA_QUALITY_REPORT_PATH
    target_path.parent.mkdir(parents=True, exist_ok=True)
    with open(target_path, mode="w", encoding="utf-8") as json_file:
        json.dump(quality_data, json_file, indent=4, ensure_ascii=False)
    return target_path


def run_pipeline(config: Optional[AppConfig] = None) -> Dict[str, Any]:
    """Execute complete ETL pipeline from scraping through reporting using configured settings."""
    app_config = config or load_config()

    pipeline_start_dt = datetime.now(timezone.utc)
    start_time_monotonic = time.time()
    logger = setup_logging(app_config.log_file_path)

    logger.info("==================================================")
    logger.info("Starting Python Web Scraping ETL Pipeline")
    logger.info("Start time: %s", pipeline_start_dt.isoformat())
    logger.info(
        "Settings: delay=%.2fs, timeout=%.1fs, max_retries=%d",
        app_config.request_delay,
        app_config.request_timeout,
        app_config.max_retries,
    )
    logger.info(
        "Sources enabled: Books=%s, Quotes=%s",
        app_config.enable_books_scraper,
        app_config.enable_quotes_scraper,
    )
    logger.info("==================================================")

    # Detect existing checkpoints on startup
    has_books_chk = has_checkpoint("Books to Scrape")
    has_quotes_chk = has_checkpoint("Quotes to Scrape")
    if has_books_chk or has_quotes_chk:
        if app_config.resume:
            logger.info("Resume mode active: will resume from detected checkpoint(s).")
        else:
            logger.info(
                "Existing checkpoint(s) detected. Run with --resume to continue from checkpoint, "
                "or --reset-checkpoint to clear them."
            )

    collected_per_source: Dict[str, int] = {
        "Books to Scrape": 0,
        "Quotes to Scrape": 0,
    }
    raw_records: List[ScrapedRecord] = []

    # 1. Scrape Books to Scrape (Isolated execution)
    if app_config.enable_books_scraper:
        logger.info("--- Phase: Scraping Books to Scrape ---")
        try:
            with BooksScraper(
                delay=app_config.request_delay,
                timeout=app_config.request_timeout,
                max_retries=app_config.max_retries,
                resume=app_config.resume,
            ) as books_scraper:
                books_raw = books_scraper.scrape()
                collected_per_source["Books to Scrape"] = len(books_raw)
                raw_records.extend(books_raw)
                logger.info(
                    "Successfully collected %d raw records from Books to Scrape.",
                    len(books_raw),
                )
        except Exception as exc:
            logger.error(
                "Books to Scrape scraper encountered an unrecoverable error: %s",
                exc,
                exc_info=True,
            )
    else:
        logger.info("Books to Scrape is disabled in configuration. Skipping.")

    # 2. Scrape Quotes to Scrape (Isolated execution)
    if app_config.enable_quotes_scraper:
        logger.info("--- Phase: Scraping Quotes to Scrape ---")
        try:
            with QuotesScraper(
                delay=app_config.request_delay,
                timeout=app_config.request_timeout,
                max_retries=app_config.max_retries,
                resume=app_config.resume,
            ) as quotes_scraper:
                quotes_raw = quotes_scraper.scrape()
                collected_per_source["Quotes to Scrape"] = len(quotes_raw)
                raw_records.extend(quotes_raw)
                logger.info(
                    "Successfully collected %d raw records from Quotes to Scrape.",
                    len(quotes_raw),
                )
        except Exception as exc:
            logger.error(
                "Quotes to Scrape scraper encountered an unrecoverable error: %s",
                exc,
                exc_info=True,
            )
    else:
        logger.info("Quotes to Scrape is disabled in configuration. Skipping.")

    # 3. Clean records
    logger.info("--- Phase: Data Cleaning ---")
    cleaned_per_source: Dict[str, int] = {
        "Books to Scrape": 0,
        "Quotes to Scrape": 0,
    }
    cleaned_records: List[ScrapedRecord] = []
    for raw in raw_records:
        cleaned = clean_record(raw)
        cleaned_records.append(cleaned)
        if cleaned.source in cleaned_per_source:
            cleaned_per_source[cleaned.source] += 1
        else:
            cleaned_per_source[cleaned.source] = 1

    logger.info(
        "Cleaning finished. Cleaned totals: Books=%d, Quotes=%d (Total=%d).",
        cleaned_per_source.get("Books to Scrape", 0),
        cleaned_per_source.get("Quotes to Scrape", 0),
        len(cleaned_records),
    )

    # 4. Validate cleaned records
    logger.info("--- Phase: Data Validation ---")
    valid_records: List[ScrapedRecord] = []
    rejected_by_reason: Dict[str, int] = {}
    total_rejected = 0

    for rec in cleaned_records:
        rejection_reasons = validate_record(rec)
        if rejection_reasons:
            total_rejected += 1
            logger.warning(
                "Rejected record [%s] '%s' (%s) due to: %s",
                rec.source,
                rec.name_or_title[:40],
                rec.source_url,
                ", ".join(rejection_reasons),
            )
            for reason in rejection_reasons:
                rejected_by_reason[reason] = rejected_by_reason.get(reason, 0) + 1
        else:
            valid_records.append(rec)

    logger.info(
        "Validation completed. Valid records: %d, Rejected records: %d.",
        len(valid_records),
        total_rejected,
    )

    # 5. Deduplicate valid records
    logger.info("--- Phase: Deduplication ---")
    unique_records, duplicate_records = find_duplicates(valid_records)
    duplicates_detected = len(duplicate_records)

    logger.info(
        "Deduplication completed. Unique records: %d, Duplicates removed: %d.",
        len(unique_records),
        duplicates_detected,
    )

    # 6. Write consolidated dataset to CSV
    logger.info("--- Phase: Exporting Final CSV Dataset ---")
    app_config.csv_output_path.parent.mkdir(parents=True, exist_ok=True)
    written_count = 0

    with open(app_config.csv_output_path, mode="w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=RECORD_FIELDS)
        writer.writeheader()
        for record in unique_records:
            writer.writerow(record.to_csv_row())
            written_count += 1

    final_record_count = written_count
    logger.info(
        "Wrote %d records to %s with UTF-8 encoding.",
        final_record_count,
        app_config.csv_output_path,
    )

    # 7. Record end time and compute duration
    pipeline_end_dt = datetime.now(timezone.utc)
    duration_seconds = round(time.time() - start_time_monotonic, 2)

    # 8. Generate JSON summary report using configured destination
    summary_report: Dict[str, Any] = {
        "collected_per_source": collected_per_source,
        "cleaned_per_source": cleaned_per_source,
        "rejected_by_reason": rejected_by_reason,
        "duplicates_detected": duplicates_detected,
        "final_record_count": final_record_count,
        "start_time": pipeline_start_dt.isoformat(),
        "end_time": pipeline_end_dt.isoformat(),
        "duration_seconds": duration_seconds,
    }

    write_summary_report(summary_report, app_config.summary_report_path)
    logger.info("Saved summary report to %s", app_config.summary_report_path)

    # 9. Generate and save Data Quality Report
    logger.info("--- Phase: Generating Data Quality Report ---")
    quality_report = generate_data_quality_report(unique_records)
    write_data_quality_report(quality_report, app_config.data_quality_report_path)
    logger.info("Saved data quality report to %s", app_config.data_quality_report_path)
    logger.info("Pipeline execution successfully completed in %.2fs", duration_seconds)

    # 10. Concise Console Summary
    print("\n" + "=" * 50)
    print("           PIPELINE RUN SUMMARY")
    print("=" * 50)
    print(f"Start Time:           {summary_report['start_time']}")
    print(f"End Time:             {summary_report['end_time']}")
    print(f"Total Duration:       {summary_report['duration_seconds']} seconds")
    print("-" * 50)
    print("Collected Per Source:")
    for src, count in collected_per_source.items():
        print(f"  - {src}: {count}")
    print("Cleaned Per Source:")
    for src, count in cleaned_per_source.items():
        print(f"  - {src}: {count}")
    print(f"Duplicates Detected:  {duplicates_detected}")
    print(f"Rejected By Reason:   {rejected_by_reason if rejected_by_reason else 'None'}")
    print(f"Final Record Count:   {final_record_count}")
    print("-" * 50)
    print(f"CSV Output:           {app_config.csv_output_path}")
    print(f"JSON Report:          {app_config.summary_report_path}")
    print(f"Quality Report:       {app_config.data_quality_report_path}")
    print(f"Log Output:           {app_config.log_file_path}")
    print("=" * 50 + "\n")

    return summary_report


def build_cli_parser() -> argparse.ArgumentParser:
    """Build and return command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="python main.py",
        description=(
            "Python Web Scraping ETL Pipeline: Scrapes Books to Scrape and Quotes to Scrape, "
            "cleans and normalizes records, validates against business rules, deduplicates via "
            "SHA-256 fingerprints, and exports consolidated CSV and JSON summary report."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--source",
        choices=["books", "quotes", "all"],
        default="all",
        help="Specify which data source to scrape: 'books', 'quotes', or 'all' (default: all).",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=None,
        metavar="SECONDS",
        help="Crawl delay between consecutive requests in seconds (overrides config).",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=None,
        metavar="SECONDS",
        help="HTTP request timeout in seconds (overrides config).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        metavar="DIR",
        help="Custom output directory for final CSV and summary report (overrides config).",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        metavar="PATH",
        help="Path to custom JSON configuration file (default: config.json).",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume scraping from the last saved checkpoint if one exists.",
    )
    parser.add_argument(
        "--reset-checkpoint",
        action="store_true",
        help="Remove all existing checkpoints and start clean.",
    )
    return parser


def resolve_config_from_args(args: argparse.Namespace) -> AppConfig:
    """Load base configuration and apply validated CLI argument overrides.

    Args:
        args: Parsed CLI namespace.

    Returns:
        AppConfig: Final merged and validated application configuration.

    Raises:
        ValueError: If any CLI argument value is out of valid bounds.
    """
    if args.delay is not None and args.delay < 0:
        raise ValueError(f"CLI argument error: --delay must be non-negative (>= 0), got {args.delay}")

    if args.timeout is not None and args.timeout <= 0:
        raise ValueError(f"CLI argument error: --timeout must be positive (> 0), got {args.timeout}")

    # Reset checkpoints if requested
    if getattr(args, "reset_checkpoint", False):
        cleared_count = clear_all_checkpoints()
        print(f"Cleared {cleared_count} existing checkpoint(s).")

    config = load_config(args.config)

    # CLI source selection overrides config toggles
    if args.source == "books":
        config.enable_books_scraper = True
        config.enable_quotes_scraper = False
    elif args.source == "quotes":
        config.enable_books_scraper = False
        config.enable_quotes_scraper = True
    elif args.source == "all":
        config.enable_books_scraper = True
        config.enable_quotes_scraper = True

    # Numeric parameter overrides
    if args.delay is not None:
        config.request_delay = args.delay
    if args.timeout is not None:
        config.request_timeout = args.timeout

    # Output directory override
    if args.output is not None:
        out_dir = Path(args.output).resolve()
        config.csv_output_path = out_dir / "final_dataset.csv"
        config.summary_report_path = out_dir / "summary_report.json"
        config.data_quality_report_path = out_dir / "data_quality_report.json"

    # Resume flag
    config.resume = bool(getattr(args, "resume", False))

    return config


def main(argv: Optional[List[str]] = None) -> None:
    """Main CLI entrypoint.

    Args:
        argv: Optional argument list for testing or programmatic invocation.
    """
    parser = build_cli_parser()
    args = parser.parse_args(argv)
    try:
        config = resolve_config_from_args(args)
    except ValueError as exc:
        parser.error(str(exc))
    run_pipeline(config)


if __name__ == "__main__":
    main()

